module.exports = [
  { publisher:'Ilta-Sanomat', tags: [], url: 'https://www.is.fi/rss/tuoreimmat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['pääkirjoitus'], url: 'https://www.is.fi/rss/paakirjoitus.xml' },
  { publisher:'Ilta-Sanomat', tags: ['kotimaa'], url: 'https://www.is.fi/rss/kotimaa.xml' },
  { publisher:'Ilta-Sanomat', tags: ['ulkomaat'], url: 'https://www.is.fi/rss/ulkomaat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['työelämä'], url: 'https://www.is.fi/rss/tyoelama.xml' },
  { publisher:'Ilta-Sanomat', tags: ['talous', 'taloussanomat'], url: 'https://www.is.fi/rss/taloussanomat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['tiede'], url: 'https://www.is.fi/rss/tiede.xml' },
  { publisher:'Ilta-Sanomat', tags: ['politiikka'], url: 'https://www.is.fi/rss/politiikka.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu'], url: 'https://www.is.fi/rss/urheilu.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/jaakiekko.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'mestarien liiga', 'jalkapallo'], url: 'https://www.is.fi/rss/mestarienliiga.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'golf'], url: 'https://www.is.fi/rss/golf.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'huuhkajat', 'jalkapallo'], url: 'https://www.is.fi/rss/huuhkajat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'koripallo'], url: 'https://www.is.fi/rss/koripallo.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'videotuomarit'], url: 'https://www.is.fi/rss/videotuomarit.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/hiihtolajit.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'lentopallo'], url: 'https://www.is.fi/rss/lentopallo.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'liiga', 'sm-liiga', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/sm-liiga.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'mäkihyppy', 'talviurheilu'], url: 'https://www.is.fi/rss/makihyppy.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'moottoripyöräily', 'moottoriurheilu'], url: 'https://www.is.fi/rss/moottoripyoraily.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'nhl', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/nhl.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'maastohiihto', 'talviurheilu', 'hiihto'], url: 'https://www.is.fi/rss/maastohiihto.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'nyrkkeily'], url: 'https://www.is.fi/rss/nyrkkeily.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'pesäpallo'], url: 'https://www.is.fi/rss/pesapallo.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'yhdistetty', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/yhdistetty.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'elitserien', 'shl', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/elitserien.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'khl', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/khl.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'mmkiekko', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/mmkiekko.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'mestis', 'jääkiekko', 'talviurheilu'], url: 'https://www.is.fi/rss/mestis.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'jalkapallo'], url: 'https://www.is.fi/rss/jalkapallo.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'veikkausliiga', 'jalkapallo'], url: 'https://www.is.fi/rss/veikkausliiga.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'valioliiga', 'jalkapallo'], url: 'https://www.is.fi/rss/valioliiga.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'eurosarjat', 'jalkapallo'], url: 'https://www.is.fi/rss/eurosarjat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'ampumahiihto', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/ampumahiihto.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'alppihiihto', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/alppihiihto.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'lumilautailu', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/lumilautailu.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'freestyle', 'hiihto', 'talviurheilu'], url: 'https://www.is.fi/rss/freestyle.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'formula1', 'f1', 'moottoriurheilu'], url: 'https://www.is.fi/rss/formula1.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'ralli', 'moottoriurheilu'], url: 'https://www.is.fi/rss/ralli.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'ravit', 'hevosurheilu'], url: 'https://www.is.fi/rss/ravit.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'purjehdus'], url: 'https://www.is.fi/rss/purjehdus.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'salibandy'], url: 'https://www.is.fi/rss/salibandy.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'taitoluistelu', 'talviurheilu'], url: 'https://www.is.fi/rss/taitoluistelu.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'tennis'], url: 'https://www.is.fi/rss/tennis.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'uinti'], url: 'https://www.is.fi/rss/uinti.xml' },
  { publisher:'Ilta-Sanomat', tags: ['urheilu', 'yleisurheilu'], url: 'https://www.is.fi/rss/yleisurheilu.xml' },
  { publisher:'Ilta-Sanomat', tags: ['viihde'], url: 'https://www.is.fi/rss/viihde.xml' },
  { publisher:'Ilta-Sanomat', tags: ['viihde', 'musiikki'], url: 'https://www.is.fi/rss/musiikki.xml' },
  { publisher:'Ilta-Sanomat', tags: ['viihde', 'horoskooppi'], url: 'https://www.is.fi/rss/horoskooppi.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'hyväolo'], url: 'https://www.is.fi/rss/hyvaolo.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'mystyle'], url: 'https://www.is.fi/rss/mystyle.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'matkat'], url: 'https://www.is.fi/rss/matkat.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'asuminen'], url: 'https://www.is.fi/rss/asuminen.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'ruoka'], url: 'https://www.is.fi/rss/ruokala/uutiset.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'ruoka'], url: 'https://www.is.fi/rss/ruokala/ajankohtaista.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'perhe'], url: 'https://www.is.fi/rss/perhe.xml' },
  { publisher:'Ilta-Sanomat', tags: ['lifestyle', 'lemmikit'], url: 'https://www.is.fi/rss/lemmikit.xml' },
  { publisher:'Ilta-Sanomat', tags: ['tekniikka', 'auto'], url: 'https://www.is.fi/rss/autot.xml' },
  { publisher:'Ilta-Sanomat', tags: ['tekniikka', 'digitoday', 'digi', 'it'], url: 'https://www.is.fi/rss/digitoday.xml' },
  { publisher:'Ilta-Sanomat', tags: ['tekniikka', 'esports', 'eurheilu'], url: 'https://www.is.fi/rss/digitoday/esports.xml' },
  { publisher:'IO-tech', tags: ['tekniikka', 'it', 'mobiili', 'atk', 'tietotekniikka'], url: 'https://www.io-tech.fi/feed/' },
  { publisher:'Iltalehti', tags: [], url: 'https://www.iltalehti.fi/rss/uutiset.xml' },
  { publisher:'Iltalehti', tags: ['urheilu'], url: 'https://www.iltalehti.fi/rss/urheilu.xml' },
  { publisher:'Iltalehti', tags: ['urheilu','jääkiekko'], url: 'https://www.iltalehti.fi/rss/jaakiekko.xml' },
  /*
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  { publisher:'Iltalehti', tags: [], url: '' },
  */
  
]

